name: Renovate
on:
  push:
    paths:
      - '.github/workflows/renovate.yml'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Run renovate
        run: npx -y renovate
        env:
          RENOVATE_CONFIG_FILE: renovate/config.js
          RENOVATE_TOKEN: ${{ secrets.MY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          RENOVATE_REPOSITORIES: KayBestmann1123/renovatetest
          LOG_LEVEL: 'debug'
